server:
  port: 8000
spring:
  application:
    name: ms-gateway
###################################################
## Configuracion Cloud para el balanceo de carga ##
###################################################
  cloud:
    gateway:
      server:
        webflux:
          routes:

            #############################################
            ## Mapeo de Rutas para el ms-auth 01 Roles ##
            #############################################
            - id: ms-auth
              uri: lb://ms-auth
              predicates:
                - Path= /api/v1/auth/roles/**
              filters:
                - RewritePath= /api/v1/auth/roles/(?<segment>.*), /api/v1/roles/${segment}


            ############################################
            ## mapeo de rutas para el auth/service 02 ##
            ############################################
            - id: ms-auth
              uri: lb://ms-auth
              predicates:
                - Path= /api/v1/auth/register
#              filters:
#                - RewritePath= /api/v1/auth/register, /api/v1/auth/register #/${segment}

            #######################################
            ## mapeo de rutas para el ms-usuario ##
            #######################################
            - id: ms-usuario
              uri: lb://ms-usuario
              predicates:
                - Path= /api/v1/usuario/**
              filters:
                - RewritePath= /api/v1/usuario/(?<segment>.*), /api/v1/${segment}

            #######################################
            ## mapeo de rutas para el ms-usuario ##
            #######################################
            - id: ms-usuario
              uri: lb://ms-usuario
              predicates:
                - Path= /api/v1/usuario/users/**
              filters:
                - RewritePath= /api/v1/usuario/users/(?<segment>.*), /api/v1/users/${segment}

###########################
## Configuracion Oauth2  ##
###########################
  security:
    oauth2:
  client:
    registration:
      gateway-client:
        provider: spring
        client-id: gateway-client
        client-secret: gateway-secret_12345
        authorization-grant-type: authorization_code
        redirect-uri: "lb://ms-gateway/authorized" ##"http://localhost:8000/authorized"
        scope: openid, profile, read, accounts.read
        client-name: gateway-client
    provider:
      spring:
        issuer-uri: "lb://ms-auth"  ###"http://localhost:8085"
  resourceserver:
    jwt:
        issuer-uri: "lb://ms-auth"  ###"http://localhost:8085"
      ##jwk-set-uri: "http://localhost:8085"

###############################################################
## para ver los logs de spring cloud gateway y loadbalancer  ##
###############################################################
logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: DEBUG
    reactor.netty.http.client: DEBUG