server:
  port: 0
  # Configuration for the Spring Boot application
spring:
  application:
    name: ms-usuario
  datasource:
    url: jdbc:postgresql://localhost:5432/users_db
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  # Hibernate JPA configuration
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
# Configuration for Eureka Client
eureka:
  client:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
#  instance:
#    prefer-ip-address: true
#    name: localhost
# Springdoc OpenAPI (Swagger) configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
    enable: true
  packages-to-scan: com.softtecnology.inmobiliaria.msusuario.controller
